
variables:
  CONTAINER_IMAGE: mcr.microsoft.com/cbl-mariner/base/core:2.0
  CONTAINER_NAME: dom0kerneltest
  CONTAINER_VOL: /linux-dom0
  CONTAINER_RT: docker

trigger:
  batch: false
  branches:
    include:
      - msft/mshv-stable
      - msft/mshv-rolling
  tags:
    include:
      - msft/mshv-rolling/*

pr:
  autoCancel: false
  drafts: false
  branches:
    include:
      - msft/mshv-stable
      - msft/mshv-rolling

jobs:
- job: Kernel
  timeoutInMinutes: 30
  strategy:
    matrix:
      'x86':
        machinePool: 'lsg-virt-amd64-1es-agent-pool-2'
      'arm64':
        machinePool: 'lsg-virt-aarch64-1es-agent-pool-2'
  pool:
    name: $(machinePool)

  steps:
  - checkout: self
    persistCredentials: true
    fetchTags: false
  - template: templates/ubuntu-20.04-build.yml
  - bash: |
      set -e
      set -x

      sudo systemctl enable --now docker

      # Allow agent to run docker operations without sudo
      sudo chmod a+rw /run/docker.sock

      $(CONTAINER_RT) pull $(CONTAINER_IMAGE)
      $(CONTAINER_RT) run -d -t --name $(CONTAINER_NAME) --volume $PWD:$(CONTAINER_VOL) $(CONTAINER_IMAGE)
      $(CONTAINER_RT) exec $(CONTAINER_NAME) $(CONTAINER_VOL)/pipelines/scripts/mariner-prepare
    displayName: 'Prepare Container'

  - bash: |
      set -e
      set -x
      $(CONTAINER_RT) exec $(CONTAINER_NAME) $(CONTAINER_VOL)/pipelines/scripts/config-validate
    displayName: 'Validate Config'

  - bash: |
      set -e
      set -x
      $(CONTAINER_RT) exec $(CONTAINER_NAME) git config --global --add safe.directory '*'
      $(CONTAINER_RT) exec -w $(CONTAINER_VOL)/ $(CONTAINER_NAME) $(CONTAINER_VOL)/pipelines/scripts/run_checkpatch.py \
        --ado-org microsoft \
        --ado-project LSG \
        --ado-access-token "$(System.AccessToken)" \
        --repo-id "$(Build.Repository.ID)" \
        --pr-id "$(System.PullRequest.PullRequestId)" \
        --source-branch "$(System.PullRequest.SourceBranch)"
    displayName: 'Run checkpatch.pl'
    condition: and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/msft/mshv-stable'))
    continueOnError: true

  - bash: |
      set -e
      set -x
      $(CONTAINER_RT) exec $(CONTAINER_NAME) $(CONTAINER_VOL)/pipelines/scripts/kernel-compile
    displayName: 'Compile Kernel'

  - bash: |
      set -e
      set -x
      $(CONTAINER_RT) rm -f $(CONTAINER_IMAGE)
    displayName: 'Cleanup container'
