#!/usr/bin/env bash

set -x
set -e

SOURCE_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "${SOURCE_ROOT}"

ARCH=$(uname -p)
if [ "$ARCH" == "aarch64" ];
then
    ARCH="arm64"
fi

make mrproper

make LC_ALL= ARCH=$ARCH mshv_defconfig
cp .config oldconfig
make LC_ALL= ARCH=$ARCH olddefconfig

diff -u oldconfig .config

