#!/usr/bin/env bash

set -x
set -e

SOURCE_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "${SOURCE_ROOT}"

ARCH=$(uname -p)
if [ "$ARCH" == "aarch64" ];
then
    ARCH="arm64"
fi

make mrproper
make LC_ALL= ARCH=$ARCH mshv_defconfig

make -j$(nproc) ARCH=$ARCH W=1
make -j$(nproc) ARCH=$ARCH W=1 modules

make -j$(nproc) ARCH=$ARCH -C tools/perf PYTHON=python3 all
make -j$(nproc) ARCH=$ARCH -C tools/bpf/bpftool
