#!/usr/bin/env bash

set -x
set -e

FLAVOR=$1

SOURCE_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "${SOURCE_ROOT}"

ARCH=$(uname -p)
if [ "$ARCH" == "aarch64" ];
then
    ARCH="arm64"
fi

make mrproper

CONFIG=mshv_defconfig
if [ "mariner" == "${FLAVOR}" ]; then
	curl -o .config https://raw.githubusercontent.com/microsoft/CBL-Mariner/main/SPECS-EXTENDED/kernel-mshv/config
	make LC_ALL= ARCH=$ARCH olddefconfig
	CONFIG=
fi

make LC_ALL= ARCH=$ARCH ${CONFIG}

make -j$(nproc) ARCH=$ARCH W=1
make -j$(nproc) ARCH=$ARCH W=1 modules

make -j$(nproc) ARCH=$ARCH -C tools/perf PYTHON=python3 all
make -j$(nproc) ARCH=$ARCH -C tools/bpf/bpftool
