#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import sys
import subprocess


if len(sys.argv) < 2:
    res = subprocess.run(["make", "kernelversion"], stdout=subprocess.PIPE)
    version = res.stdout.decode("ascii").strip()
    ref = "HEAD"
else:
    # Ref might look like refs/tags/msft/mshv-rolling/5.15.74.mshv3.
    parts = sys.argv[1].split("/")
    version = parts[len(parts)-1]
    if len(parts) > 3:
        ref = sys.argv[1][len("refs/tags/"):]
    else:
        ref = sys.argv[1]


tarball_format = "tar"
tarball_prefix = "kernel-mshv-{}".format(version)
tarball_tar = "{}.{}".format(tarball_prefix, tarball_format)
tarball_name = "{}.gz".format(tarball_tar)

cmds = [
         ["git", "archive", "--format={}".format(tarball_format),
             "--prefix={}/".format(tarball_prefix), 
             "--output={}".format(tarball_tar), ref],
         ["tar", "--delete", "-f", tarball_tar, "{}/pipelines".format(tarball_prefix)],
         ["gzip", "-9", tarball_tar]
    ]

for cmd in cmds:
    print(" ".join(cmd))
    res = subprocess.run(cmd)
    if 0 != res.returncode:
        err = res.stderr.decode("ascii")
        raise Exception(err)

