#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import os
import sys
import subprocess
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from lsgtools import log
from lsgtools.virt.mshv import kernel

if len(sys.argv) < 2:
    version = kernel.get_version_local()
    ref = "HEAD"
else:
    version = kernel.get_version_from_tag(sys.argv[1])
    # Ref might look like refs/tags/msft/mshv-rolling/5.15.74.mshv3.
    if len(sys.argv[1].split("/")) > 3:
        ref = sys.argv[1][len("refs/tags/"):]
    else:
        ref = sys.argv[1]


tarball_format = kernel.get_tarball_format()
tarball_prefix = kernel.build_tarball_prefix(version)
tarball_tar = kernel.build_tar_name(version)
tarball_name = kernel.build_tgz_name(version)

cmds = [
         ["git", "archive", "--format={}".format(tarball_format),
             "--prefix={}/".format(tarball_prefix), 
             "--output={}".format(tarball_tar), ref],
         ["tar", "--delete", "-f", tarball_tar, "{}/pipelines".format(tarball_prefix)],
         ["gzip", "-9", tarball_tar]
    ]

for cmd in cmds:
    log.debug(" ".join(cmd))
    res = subprocess.run(cmd)
    if 0 != res.returncode:
        err = res.stderr.decode("ascii")
        raise Exception(err)

