#!/usr/bin/env python3

__copyright__ = "Copyright (c) Microsoft Corporation."

import os
import sys
import re
import subprocess
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from lsgtools.virt.mshv import kernel

if len(sys.argv) < 2:
    print("Usage: {} <tag name to validate>".format(sys.argv[0]))
    sys.exit(0)


tag_version = kernel.get_version_from_tag(sys.argv[1])

if not kernel.is_version_valid(tag_version):
    print("Invalid tag name '{}'".format(sys.argv[1]))
    sys.exit(1)


mf_version = kernel.get_version_local()

if not tag_version == mf_version:
    print("Versions tag vs Makefile don't match: '{}' != '{}'".format(tag_version, mf_version))
    sys.exit(1)

print("Tag '{}' is valid".format(sys.argv[1]))

sys.exit(0)
